import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import type { InferGetStaticPropsType, GetStaticProps } from 'next'
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
  message: string;
}

export default function Home({ message }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App - SUB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          Home (Sub)
          <br/>
          <Link href="/my">
            Link to My Page
          </Link>
        </div>

        <p>
          {message}
        </p>
      </main>
    </>
  );
}

export const getStaticProps = (async () => {
  return {
    props: {
      message: 'Hello from getStaticProps!',
    }
  }
}) satisfies GetStaticProps<HomeProps>
